[[policy]]
= Community Support Policy

One of the key goals of the http://www.payara.org[Payara Foundation] is to interact with our community userbase and understand their needs and how are they engaging with the Payara Platform Community Edition in general. To this effect, it is important to outline the guidelines that compose our policy on how to properly handle user requests.

[[questions]]
== Questions and General Advice

For questions regarding any of the platform, including configuration, visit the http://www.payara.org/forum[Payara Forum] and create a topic to discuss your inquiries in detail. This includes advice on:

* Configuration of any Payara Platform products
* Integration of the Payara Platform with other technologies
* Software Architecture and Best Practices
* etc.

[[user-requests]]
== User Requests

Users can request assistance by either reporting existing bugs/defects in any of the products of the Payara Platform or by requesting the implementation of specific enhancements for any existing feature sets. To this effect, a community user should raise an issue in the project's issue tracker and follow the template to make sure that all details are included.

This doesn't mean that we'll guarantee the resolution of these issues right away. Once an issue has been analyzed by our engineers, the following outcomes can occur:

* We'll accept the user's request and escalate the issue to our Platform Development team so that the issue is implemented in a future release. We don't give a guarantee when the issue is going to be shipped.
* We'll reject the user's request and close the issue if the issue is not aligned with our Community Support guidelines
* We'll submit the issue to community voting, where it will transition to an open vote where other members of the community can give their support to the issue being implemented in the future.

[[bug-reports]]
=== Bug Reports

In case you want to report a bug or defect present in any of the main products of the Payara Platform Community Edition (Server, Micro, Embedded, API), keep in mind the following:

* We won't accept any bug reports that we can't reproduce. Please make sure to include a http://sscce.org/[Short, Self Contained and Correct Example] scenario that we can use to verify the presence of the bug being reported.
* We won't accept any bug reports that were tested on the **current release** of the Community Edition. If you encountered the bug on a previous release, make sure to test the same scenario in the very release before raising an issue.
* Please, **be involved as much as possible** with the engineers assigned to your issue. If you do not share the necessary information or remain silent while we await crucial details on the issue, then we'll proceed to close the issue without any proper resolution.

As mentioned previously, we reserve the right to either accept, reject or submit any issues to community voting based on the goals of our Platform development team and the product landscape in general. We'll follow these guidelines were possible:

* We'll **immediately accept** any issues that relate to:
** Critical show-stopping defects (domain startup fails, HTTP service breaks, etc.)
** Security Vulnerabilities
** Defects introduced in recently implemented feature sets
** Jakarta EE & Eclipse MicroProfile specification compatibility
** Payara Micro specific features
* We'll **immediately reject** any issues that relate to:
** Integration with Frameworks and APIs that are outside the Jakarta EE & Eclipse MicroProfile platforms (like Dropwizard, Spring Framework, etc)
** Integration of third-party implementations of Jakarta EE APIs like Hibernate, OpenJPA, etc.
** Client applications that use the Payara Embedded dependencies
** Require a complex setup with external systems like RDBMS/NoSQL databases, LDAP directories, etc.  
* Every other bug report will be submitted to **community voting**

[[enhancements]]
=== Enhancements

In case you want to request an enhancement to any of the products of the Payara Platform, keep in mind the following:

* We'll only accept requests for what we consider minor enhancements or improvements like these examples:
** Adding new arguments to an `asadmin` command
** Expanding the usability of a Web Admin Console view
** Improving the logging entries generated by an internal Payara Server module
* Please check all of the current issues that are part of the **Open Roadmap** (issues labelled with `Type:Roadmap`) to be sure that a feature set that you'd like to have implemented is already planned for a future release. 
* If you see that your request is already part of the **Open Roadmap**, consider participating in the conversation of this issue to contribute any details you think might be good to consider on our part.

As mentioned previously, we reserve the right to either reject or submit any issues to community voting based on the goals of our Platform development team and the product landscape in general. We'll follow these guidelines were possible:

* We'll immediately reject any requests that relate to:
** The implementation of big feature sets, like the items in the current **Open Roadmap**
** "Legacy" APIs or internal feature sets that are too old to be properly used for modern application development like:
*** EJB 2.x
*** JAX-WS/ Metro
*** JCA & JMS
*** JSP
** Client applications that use the Payara Embedded dependencies
* Every other bug report will be submitted to **community voting**

[[contributing]]
=== Community Contributions

Before submitting any issue to the voting process, we may suggest to the requester to implement the issue themselves if they are confident enough. As the Payara Platform Community Edition is an Open source project, any user is in the capacity to contribute code to the platform, which might be a better solution for their requirements instead. Read the general guidelines on how to contribute in our https://docs.payara.fish/community[official documentation].

NOTE: We can't guarantee complete assistance if any users wish to contribute by themselves and handle their request, so keep this in mind if you want to embark on this effort beforehand.

[[voting]]
=== Voting Process

Once an issue has been submitted to an open vote, we'll leave the issue open so that other members of the community can express their support. The general process is quite simple:

* To vote on an issue just give a thumbs-up 👍 to the issue's first message. Any user with a GitHub account can do this.
* Any community user can also express their disapproval of any issue being implemented by giving a thumbs-down 👎 to the issue's first message.
* The vote tally will be the difference between positive and negative votes.
* At the end of every month, we'll select the top voted issues (1 or 2 depending on the landscape of platform development) and accept/escalate them right away.
* All issues will compete in the vote regardless of whether they are bug reports or enhancement requests.
* Only issues with **2 or more positive votes** will be considered for selection.
* In case of a tie, the issue **that was raised first will be selected first**.
* All other issues which are not select will retain their votes and will have another chance the following month.

IMPORTANT: Keep in mind that an issue that has been escalated after being selected still has not a guarantee when its implementation will be ready in a future release.

To keep track of the current top-voted issues we recommend to use https://vote.biglybt.com/payara/Payara/Status:%20Voting[this website], which allows any user to quickly vote for their issues as well.

Keep in mind that issues can't remain endlessly waiting for their turn to be picked up. Our intention is to use our resources efficiently to implement any requests that are of the interest of our community in general and for this reason, they must be veto-ed through voting first. If after an issue spends `N` months in open voting without clearing the bar of selection, we'll proceed to close the issue. `N` will be:

* **3 months** for bug reports
* **6 months** for enhancement requests

WARNING: We understand that you may reopen the issue in the case that you want to give it another chance of being selected, but ask you not to do so. If you want us to reconsider its implementation, please raise a new issue and properly explain in detail to the general community why the issue should be selected. This way the issue will start again with `0` votes with a fair chance to be selected if the community is interested in it.