/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright (c) 2026 Payara Foundation and/or its affiliates. All rights reserved.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common Development
 * and Distribution License("CDDL") (collectively, the "License").  You
 * may not use this file except in compliance with the License.  You can
 * obtain a copy of the License at
 * https://github.com/payara/Payara/blob/main/LICENSE.txt
 * See the License for the specific
 * language governing permissions and limitations under the License.
 *
 * When distributing the software, include this License Header Notice in each
 * file and include the License file at legal/OPEN-SOURCE-LICENSE.txt.
 *
 * GPL Classpath Exception:
 * The Payara Foundation designates this particular file as subject to the "Classpath"
 * exception as provided by the Payara Foundation in the GPL Version 2 section of the License
 * file that accompanied this code.
 *
 * Modifications:
 * If applicable, add the following below the License Header, with the fields
 * enclosed by brackets [] replaced by your own identifying information:
 * "Portions Copyright [year] [name of copyright owner]"
 *
 * Contributor(s):
 * If you wish your version of this file to be governed by only the CDDL or
 * only the GPL Version 2, indicate your decision by adding "[Contributor]
 * elects to include this software in this distribution under the [CDDL or GPL
 * Version 2] license."  If you don't indicate a single choice of license, a
 * recipient has the option to distribute your version of this file under
 * either the CDDL, the GPL Version 2 or to extend the choice of license to
 * its licensees as provided above.  However, if you add GPL Version 2 code
 * and therefore, elected the GPL Version 2 license, then the option applies
 * only if the new code is made subject to such option by the copyright
 * holder.
 */

/**
 * JPMS module descriptor for the Payara MicroProfile OpenAPI appserver integration module.
 *
 * OSGi metadata continues to be generated by Bnd (maven-bundle-plugin) — the dual-presence strategy.
 *
 * Automatic-module note: hk2-api, hk2-runlevel, hk2-config, web-glue, and Payara internal
 * modules appear as automatic modules. microprofile-openapi-api ships an explicit
 * module-info.class (named module org.eclipse.microprofile.openapi).
 *
 * SPI note: two providers live in this module:
 *   - OASFactoryResolverImpl → org.eclipse.microprofile.openapi.spi.OASFactoryResolver
 *   - OpenApiServletContainerInitializer → jakarta.servlet.ServletContainerInitializer
 * Both 'provides' declarations are included; META-INF/services files are retained for OSGi.
 *
 * @Configured note: OpenApiServiceConfiguration has a manually maintained ConfigInjector
 * (same AP limitation as healthcheck and metrics).
 */
module fish.payara.microprofile.openapi {

    // ── Spec and standard Jakarta APIs ───────────────────────────────────────
    // named module: microprofile-openapi-api ships module-info.class
    requires org.eclipse.microprofile.openapi;
    // automatic module: microprofile-config-api → org.eclipse.microprofile.config
    requires org.eclipse.microprofile.config;
    // named modules
    requires jakarta.annotation;
    requires jakarta.cdi;
    requires jakarta.inject;
    requires jakarta.json;
    requires jakarta.ws.rs;
    requires jakarta.servlet;

    // ── Payara internal modules (automatic) ───────────────────────────────────
    // microprofile-connector-*.jar → microprofile.connector
    requires microprofile.connector;
    // microprofile-common-*.jar → microprofile.common  (SetSecureMicroprofileConfigurationCommand)
    requires microprofile.common;
    // web-glue-*.jar → web.glue  (com.sun.enterprise.web.*)
    requires web.glue;
    // internal-api-*.jar → internal.api
    requires internal.api;

    // ── Additional Jakarta APIs ───────────────────────────────────────────────
    // jakarta.validation-api (named) → jakarta.validation  (used by ApplicationProcessor, OpenApiWalker)
    requires jakarta.validation;
    // jakarta.xml.bind-api (named) → jakarta.xml.bind  (used by OpenApiWalker)
    requires jakarta.xml.bind;

    // ── GlassFish server internals (automatic) ────────────────────────────────
    // kernel-*.jar → kernel  (com.sun.enterprise.v3.server.*, com.sun.enterprise.v3.services.impl.*)
    requires kernel;
    // grizzly-config-*.jar → grizzly.config  (org.glassfish.grizzly.config.dom.*)
    requires grizzly.config;
    // class-model-*.jar → org.glassfish.hk2.classmodel  (org.glassfish.hk2.classmodel.reflect.*)
    requires org.glassfish.hk2.classmodel;

    // ── Jersey server (named) ─────────────────────────────────────────────────
    // jersey-server (named) → org.glassfish.jersey.core.server  (used by OpenApiApplication)
    requires org.glassfish.jersey.core.server;

    // ── Third-party named modules ─────────────────────────────────────────────
    // jackson-core (named MR) → com.fasterxml.jackson.core
    requires com.fasterxml.jackson.core;
    // jackson-databind (named MR) → com.fasterxml.jackson.databind
    requires com.fasterxml.jackson.databind;
    // jackson-dataformat-yaml (named MR) → com.fasterxml.jackson.dataformat.yaml
    requires com.fasterxml.jackson.dataformat.yaml;
    // jersey-container-servlet (named) → org.glassfish.jersey.container.servlet
    requires org.glassfish.jersey.container.servlet;

    // ── HK2 (automatic modules) ───────────────────────────────────────────────
    requires org.glassfish.hk2.api;
    requires org.glassfish.hk2.runlevel;
    requires hk2.config;

    // ── GlassFish deployment / admin APIs (automatic) ────────────────────────
    requires glassfish.api;
    requires config.api;
    requires common.util;

    // ── JDK modules ───────────────────────────────────────────────────────────
    requires java.logging;
    requires java.desktop;

    // ── Exported packages ─────────────────────────────────────────────────────
    exports fish.payara.microprofile.openapi.activation;
    exports fish.payara.microprofile.openapi.api;
    exports fish.payara.microprofile.openapi.api.processor;
    exports fish.payara.microprofile.openapi.api.visitor;
    exports fish.payara.microprofile.openapi.impl;
    exports fish.payara.microprofile.openapi.impl.admin;
    exports fish.payara.microprofile.openapi.impl.config;
    exports fish.payara.microprofile.openapi.impl.model;
    exports fish.payara.microprofile.openapi.impl.model.callbacks;
    exports fish.payara.microprofile.openapi.impl.model.examples;
    exports fish.payara.microprofile.openapi.impl.model.headers;
    exports fish.payara.microprofile.openapi.impl.model.info;
    exports fish.payara.microprofile.openapi.impl.model.links;
    exports fish.payara.microprofile.openapi.impl.model.media;
    exports fish.payara.microprofile.openapi.impl.model.parameters;
    exports fish.payara.microprofile.openapi.impl.model.responses;
    exports fish.payara.microprofile.openapi.impl.model.security;
    exports fish.payara.microprofile.openapi.impl.model.servers;
    exports fish.payara.microprofile.openapi.impl.model.tags;
    exports fish.payara.microprofile.openapi.impl.model.util;
    exports fish.payara.microprofile.openapi.impl.processor;
    exports fish.payara.microprofile.openapi.impl.rest.app.provider;
    exports fish.payara.microprofile.openapi.impl.rest.app.provider.mixin;
    exports fish.payara.microprofile.openapi.impl.rest.app.provider.writer;
    exports fish.payara.microprofile.openapi.impl.rest.app.service;
    exports fish.payara.microprofile.openapi.impl.rest.init;
    exports fish.payara.microprofile.openapi.impl.visitor;
    exports fish.payara.microprofile.openapi.rest.app;
    exports fish.payara.microprofile.openapi.util;

    // ── Deep opens for HK2 inhabitant scanning and CDI proxy generation ───────
    opens fish.payara.microprofile.openapi.activation;
    opens fish.payara.microprofile.openapi.api;
    opens fish.payara.microprofile.openapi.api.processor;
    opens fish.payara.microprofile.openapi.api.visitor;
    opens fish.payara.microprofile.openapi.impl;
    opens fish.payara.microprofile.openapi.impl.admin;
    opens fish.payara.microprofile.openapi.impl.config;
    opens fish.payara.microprofile.openapi.impl.model;
    opens fish.payara.microprofile.openapi.impl.model.callbacks;
    opens fish.payara.microprofile.openapi.impl.model.examples;
    opens fish.payara.microprofile.openapi.impl.model.headers;
    opens fish.payara.microprofile.openapi.impl.model.info;
    opens fish.payara.microprofile.openapi.impl.model.links;
    opens fish.payara.microprofile.openapi.impl.model.media;
    opens fish.payara.microprofile.openapi.impl.model.parameters;
    opens fish.payara.microprofile.openapi.impl.model.responses;
    opens fish.payara.microprofile.openapi.impl.model.security;
    opens fish.payara.microprofile.openapi.impl.model.servers;
    opens fish.payara.microprofile.openapi.impl.model.tags;
    opens fish.payara.microprofile.openapi.impl.model.util;
    opens fish.payara.microprofile.openapi.impl.processor;
    opens fish.payara.microprofile.openapi.impl.rest.app.provider;
    opens fish.payara.microprofile.openapi.impl.rest.app.provider.mixin;
    opens fish.payara.microprofile.openapi.impl.rest.app.provider.writer;
    opens fish.payara.microprofile.openapi.impl.rest.app.service;
    opens fish.payara.microprofile.openapi.impl.rest.init;
    opens fish.payara.microprofile.openapi.impl.visitor;
    opens fish.payara.microprofile.openapi.rest.app;
    opens fish.payara.microprofile.openapi.util;

    // ── SPI ───────────────────────────────────────────────────────────────────
    provides org.eclipse.microprofile.openapi.spi.OASFactoryResolver
            with fish.payara.microprofile.openapi.impl.model.OASFactoryResolverImpl;
    provides jakarta.servlet.ServletContainerInitializer
            with fish.payara.microprofile.openapi.impl.rest.init.OpenApiServletContainerInitializer;
}