FROM @docker.basic4tests.image@

EXPOSE 4848 9009 8080 8181 3700 3820 3920 8686 6666 4900 5900

USER payara
WORKDIR ${HOME_DIR}

ENV DOMAIN_NAME=test

COPY --chown=payara:payara maven/artifacts/@docker.payara.rootDirectoryName@ ${PAYARA_DIR}/

RUN true \
    && set -x \
    && echo "AS_ADMIN_PASSWORD=${ADMIN_PASSWORD}" >> ${PASSWORD_FILE} \
    && ${PAYARA_DIR}/bin/asadmin --user=${ADMIN_USER} --passwordfile=${PASSWORD_FILE} create-domain --keytooloptions CN=localhost ${DOMAIN_NAME} \
    && ${PAYARA_DIR}/bin/asadmin start-domain ${DOMAIN_NAME} \
    && ${PAYARA_DIR}/bin/asadmin --user=${ADMIN_USER} --passwordfile=${PASSWORD_FILE} enable-secure-admin \
    && ${PAYARA_DIR}/bin/asadmin --user=${ADMIN_USER} --passwordfile=${PASSWORD_FILE} create-jvm-options \
      --target default-config '-Xss${ENV=MEM_XSS}:\-Dhazelcast.discovery.enabled=false)' \
    && ${PAYARA_DIR}/bin/asadmin stop-domain ${DOMAIN_NAME} \
    && true
