/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright (c) 2026 Payara Foundation and/or its affiliates. All rights reserved.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common Development
 * and Distribution License("CDDL") (collectively, the "License").  You
 * may not use this file except in compliance with the License.  You can
 * obtain a copy of the License at
 * https://github.com/payara/Payara/blob/main/LICENSE.txt
 * See the License for the specific
 * language governing permissions and limitations under the License.
 *
 * When distributing the software, include this License Header Notice in each
 * file and include the License file at legal/OPEN-SOURCE-LICENSE.txt.
 *
 * GPL Classpath Exception:
 * The Payara Foundation designates this particular file as subject to the "Classpath"
 * exception as provided by the Payara Foundation in the GPL Version 2 section of the License
 * file that accompanied this code.
 *
 * Modifications:
 * If applicable, add the following below the License Header, with the fields
 * enclosed by brackets [] replaced by your own identifying information:
 * "Portions Copyright [year] [name of copyright owner]"
 *
 * Contributor(s):
 * If you wish your version of this file to be governed by only the CDDL or
 * only the GPL Version 2, indicate your decision by adding "[Contributor]
 * elects to include this software in this distribution under the [CDDL or GPL
 * Version 2] license."  If you don't indicate a single choice of license, a
 * recipient has the option to distribute your version of this file under
 * either the CDDL, the GPL Version 2 or to extend the choice of license to
 * its licensees as provided above.  However, if you add GPL Version 2 code
 * and therefore, elected the GPL Version 2 license, then the option applies
 * only if the new code is made subject to such option by the copyright
 * holder.
 */

/**
 * JPMS module descriptor for the Payara MicroProfile Config appserver integration module.
 *
 * OSGi metadata continues to be generated by Bnd (maven-bundle-plugin) from the compiled
 * bytecode and pom.xml, so both MANIFEST.MF (OSGi) and module-info.class (JPMS) are
 * present in the produced JAR — the dual-presence strategy.
 *
 * Automatic-module note: several dependencies below (microprofile-config-api, hk2-api,
 * class-model, Payara internal modules) do not yet have their own module-info.java and
 * appear on the module path as automatic modules with the derived names used here.
 *
 * SPI note: this module keeps META-INF/services/org.eclipse.microprofile.config.spi.ConfigProviderResolver
 * pointing to ConfigProviderResolverSync (which lives in microprofile-config-service).
 * As a named JPMS module, that services file is invisible to JPMS ServiceLoader — only an explicit
 * 'provides' declaration would be used by the JVM. Because the implementation class is in a different
 * module a cross-module 'provides' is illegal in JPMS, so this module only declares 'uses'.
 * OSGi reads META-INF/services files independently of JPMS, so the production OSGi runtime still
 * discovers the shim correctly.
 * Future: once microprofile-config-service has its own module-info.java, add 'provides' there and
 * remove the META-INF/services file from this module.
 */
module fish.payara.microprofile.config {

    // ── Spec and standard Jakarta APIs ───────────────────────────────────────
    // automatic module: microprofile-config-api-*.jar → org.eclipse.microprofile.config
    requires org.eclipse.microprofile.config;
    // named modules
    requires jakarta.annotation;
    requires jakarta.cdi;
    requires jakarta.inject;

    // ── Payara internal modules (all automatic: no module-info.java yet) ─────
    // microprofile-config-service-*.jar → microprofile.config.service
    requires microprofile.config.service;
    // microprofile-connector-*.jar → microprofile.connector
    requires microprofile.connector;
    // internal-api-*.jar → internal.api
    requires internal.api;
    // weld-integration-*.jar → weld.integration  (used by ConfigDeployer via WeldDeployer)
    requires weld.integration;

    // ── HK2 (automatic modules) ───────────────────────────────────────────────
    // hk2-api-*.jar → org.glassfish.hk2.api  (includes org.jvnet.hk2.annotations)
    requires org.glassfish.hk2.api;
    // class-model-*.jar → org.glassfish.hk2.classmodel  (Types scanning in ConfigDeployer)
    requires org.glassfish.hk2.classmodel;

    // ── GlassFish deployment APIs (automatic) ────────────────────────────────
    // glassfish-api-*.jar → glassfish.api
    requires glassfish.api;

    // ── JDK modules not included in java.base ────────────────────────────────
    // java.util.logging (Logger, Level) — used in ConfigPropertiesProducer
    requires java.logging;

    // ── Exported packages (all three packages are part of the public API) ────
    exports fish.payara.microprofile.config.activation;
    exports fish.payara.microprofile.config.cdi;
    exports fish.payara.microprofile.config.cdi.model;

    // ── Deep opens for runtime framework access ───────────────────────────────
    // HK2 inhabitant generator scans annotations in activation classes at startup.
    // CDI container (Weld) creates proxies for CDI beans and portable extensions.
    // Unqualified opens also allow Mockito / JUnit reflection from the unnamed module
    // when running tests on the module path.
    opens fish.payara.microprofile.config.activation;
    opens fish.payara.microprofile.config.cdi;
    opens fish.payara.microprofile.config.cdi.model;

    // ── SPI ───────────────────────────────────────────────────────────────────
    // This module is a CONSUMER of ConfigProviderResolver.
    // The META-INF/services file in this module (for OSGi) points to
    // ConfigProviderResolverSync in microprofile-config-service, but JPMS
    // ServiceLoader ignores META-INF/services in named modules — only a
    // 'provides' declaration matters for the JVM module system. A cross-module
    // 'provides' is illegal in JPMS, so no 'provides' is declared here.
    // When microprofile-config-service gains module-info.java, move 'provides' there.
    uses org.eclipse.microprofile.config.spi.ConfigProviderResolver;
}
