/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright (c) 2026 Payara Foundation and/or its affiliates. All rights reserved.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common Development
 * and Distribution License("CDDL") (collectively, the "License").  You
 * may not use this file except in compliance with the License.  You can
 * obtain a copy of the License at
 * https://github.com/payara/Payara/blob/main/LICENSE.txt
 * See the License for the specific
 * language governing permissions and limitations under the License.
 *
 * When distributing the software, include this License Header Notice in each
 * file and include the License file at legal/OPEN-SOURCE-LICENSE.txt.
 *
 * GPL Classpath Exception:
 * The Payara Foundation designates this particular file as subject to the "Classpath"
 * exception as provided by the Payara Foundation in the GPL Version 2 section of the License
 * file that accompanied this code.
 *
 * Modifications:
 * If applicable, add the following below the License Header, with the fields
 * enclosed by brackets [] replaced by your own identifying information:
 * "Portions Copyright [year] [name of copyright owner]"
 *
 * Contributor(s):
 * If you wish your version of this file to be governed by only the CDDL or
 * only the GPL Version 2, indicate your decision by adding "[Contributor]
 * elects to include this software in this distribution under the [CDDL or GPL
 * Version 2] license."  If you don't indicate a single choice of license, a
 * recipient has the option to distribute your version of this file under
 * either the CDDL, the GPL Version 2 or to extend the choice of license to
 * its licensees as provided above.  However, if you add GPL Version 2 code
 * and therefore, elected the GPL Version 2 license, then the option applies
 * only if the new code is made subject to such option by the copyright
 * holder.
 */

/**
 * JPMS module descriptor for the Payara MicroProfile Fault Tolerance appserver integration module.
 *
 * OSGi metadata continues to be generated by Bnd (maven-bundle-plugin) from the compiled
 * bytecode and pom.xml — the dual-presence strategy.
 *
 * Automatic-module note: microprofile-fault-tolerance-api, hk2-api, hk2-runlevel, hk2-config,
 * requesttracing-core, opentelemetry-tracing-starter, payara-api, and other Payara internal
 * modules appear as automatic modules on the module path with the derived names used here.
 *
 * SPI note: this module has no META-INF/services registrations, so no 'provides' is declared.
 * The @Configured interface FaultToleranceServiceConfiguration requires a manually maintained
 * ConfigInjector (same reason as healthcheck — the hk2 config-generator AP does not generate
 * source files when compiling as a JPMS named module).
 */
module fish.payara.microprofile.faulttolerance {

    // ── Spec and standard Jakarta APIs ───────────────────────────────────────
    // automatic module: microprofile-fault-tolerance-api → microprofile.fault.tolerance.api
    requires microprofile.fault.tolerance.api;
    // automatic module: microprofile-config-api → org.eclipse.microprofile.config (used for FT config)
    requires org.eclipse.microprofile.config;
    // named modules
    requires jakarta.annotation;
    requires jakarta.cdi;
    requires jakarta.inject;
    requires jakarta.concurrency;

    // ── Payara internal modules (automatic) ───────────────────────────────────
    // microprofile-connector-*.jar → microprofile.connector
    requires microprofile.connector;
    // microprofile-metrics-*.jar (Payara impl, named once modularized)
    requires fish.payara.microprofile.metrics;
    // payara-api-*.jar → payara.api  (fish.payara.notification.requesttracing.*)
    requires payara.api;
    // requesttracing-core-*.jar → requesttracing.core  (fish.payara.nucleus.requesttracing.*)
    requires requesttracing.core;
    // opentelemetry-tracing-starter-*.jar → opentelemetry.tracing.starter  (fish.payara.opentracing.*)
    requires opentelemetry.tracing.starter;

    // ── OpenTelemetry (automatic modules) ────────────────────────────────────
    // opentelemetry-api-*.jar → io.opentelemetry.api
    requires io.opentelemetry.api;

    // ── HK2 (automatic modules) ───────────────────────────────────────────────
    requires org.glassfish.hk2.api;
    requires org.glassfish.hk2.runlevel;
    requires hk2.config;

    // ── GlassFish deployment / admin APIs (automatic) ────────────────────────
    requires glassfish.api;
    requires config.api;
    requires common.util;
    requires internal.api;

    // ── JDK modules ───────────────────────────────────────────────────────────
    requires java.logging;
    // javax.naming (JNDI) — used to look up ManagedExecutorService from JNDI
    requires java.naming;
    // java.sql — used in test code (AnnotationInvalidTest)
    requires java.sql;
    // javassist is a transitive Weld/CDI classpath dep (unnamed module);
    // the pom adds --add-reads fish.payara.microprofile.faulttolerance=ALL-UNNAMED

    // ── Exported packages ─────────────────────────────────────────────────────
    exports fish.payara.microprofile.faulttolerance;
    exports fish.payara.microprofile.faulttolerance.activation;
    exports fish.payara.microprofile.faulttolerance.admin;
    exports fish.payara.microprofile.faulttolerance.cdi;
    exports fish.payara.microprofile.faulttolerance.otel;
    exports fish.payara.microprofile.faulttolerance.policy;
    exports fish.payara.microprofile.faulttolerance.service;
    exports fish.payara.microprofile.faulttolerance.state;

    // ── Deep opens for HK2 inhabitant scanning and CDI proxy generation ───────
    opens fish.payara.microprofile.faulttolerance;
    opens fish.payara.microprofile.faulttolerance.activation;
    opens fish.payara.microprofile.faulttolerance.admin;
    opens fish.payara.microprofile.faulttolerance.cdi;
    opens fish.payara.microprofile.faulttolerance.otel;
    opens fish.payara.microprofile.faulttolerance.policy;
    opens fish.payara.microprofile.faulttolerance.service;
    opens fish.payara.microprofile.faulttolerance.state;
}