/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright (c) 2026 Payara Foundation and/or its affiliates. All rights reserved.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common Development
 * and Distribution License("CDDL") (collectively, the "License").  You
 * may not use this file except in compliance with the License.  You can
 * obtain a copy of the License at
 * https://github.com/payara/Payara/blob/main/LICENSE.txt
 * See the License for the specific
 * language governing permissions and limitations under the License.
 *
 * When distributing the software, include this License Header Notice in each
 * file and include the License file at legal/OPEN-SOURCE-LICENSE.txt.
 *
 * GPL Classpath Exception:
 * The Payara Foundation designates this particular file as subject to the "Classpath"
 * exception as provided by the Payara Foundation in the GPL Version 2 section of the License
 * file that accompanied this code.
 *
 * Modifications:
 * If applicable, add the following below the License Header, with the fields
 * enclosed by brackets [] replaced by your own identifying information:
 * "Portions Copyright [year] [name of copyright owner]"
 *
 * Contributor(s):
 * If you wish your version of this file to be governed by only the CDDL or
 * only the GPL Version 2, indicate your decision by adding "[Contributor]
 * elects to include this software in this distribution under the [CDDL or GPL
 * Version 2] license."  If you don't indicate a single choice of license, a
 * recipient has the option to distribute your version of this file under
 * either the CDDL, the GPL Version 2 or to extend the choice of license to
 * its licensees as provided above.  However, if you add GPL Version 2 code
 * and therefore, elected the GPL Version 2 license, then the option applies
 * only if the new code is made subject to such option by the copyright
 * holder.
 */

/**
 * JPMS module descriptor for the Payara MicroProfile Metrics appserver integration module.
 *
 * OSGi metadata continues to be generated by Bnd (maven-bundle-plugin) — the dual-presence strategy.
 *
 * Automatic-module note: microprofile-metrics-api, hk2-api, hk2-runlevel, hk2-config,
 * payara-executor-service, healthcheck-core, web-glue, weld-integration, and other Payara
 * internal modules appear as automatic modules on the module path.
 *
 * SPI note: MetricsServletContainerInitializer is the provider of ServletContainerInitializer
 * in this module. A 'provides' declaration is included for JPMS ServiceLoader compliance.
 * The META-INF/services file is retained for OSGi runtime compatibility.
 *
 * @Configured note: MetricsServiceConfiguration has a manually maintained ConfigInjector
 * because the hk2 config-generator AP does not generate sources under JPMS module-aware
 * compilation. Must be kept in sync with @Attribute declarations on MetricsServiceConfiguration.
 */
module fish.payara.microprofile.metrics {

    // ── Spec and standard Jakarta APIs ───────────────────────────────────────
    // automatic module: microprofile-metrics-api → microprofile.metrics.api
    requires microprofile.metrics.api;
    // automatic module: microprofile-config-api → org.eclipse.microprofile.config
    requires org.eclipse.microprofile.config;
    // named modules
    requires jakarta.annotation;
    requires jakarta.cdi;
    requires jakarta.inject;
    requires jakarta.json;
    requires jakarta.servlet;

    // ── Payara internal modules (automatic) ───────────────────────────────────
    // microprofile-connector-*.jar → microprofile.connector
    requires microprofile.connector;
    // microprofile-common-*.jar → microprofile.common  (SetSecureMicroprofileConfigurationCommand)
    requires microprofile.common;
    // payara-executor-service-*.jar → payara.executor.service
    requires payara.executor.service;
    // healthcheck-core-*.jar → healthcheck.core  (fish.payara.nucleus.healthcheck.*)
    requires healthcheck.core;
    // web-glue-*.jar → web.glue  (com.sun.enterprise.web.*)
    requires web.glue;
    // weld-integration-*.jar → weld.integration
    requires weld.integration;
    // internal-api-*.jar → internal.api
    requires internal.api;

    // ── Additional Jakarta APIs ───────────────────────────────────────────────
    // jakarta.xml.bind-api (named) → jakarta.xml.bind  (used by MetricsMetadata, XmlTag JMX config)
    requires jakarta.xml.bind;
    // jakarta.ws.rs-api (named) → jakarta.ws.rs  (used by MetricsResource REST endpoint)
    requires jakarta.ws.rs;

    // ── HK2 class-model (automatic) ──────────────────────────────────────────
    // class-model-*.jar → org.glassfish.hk2.classmodel  (used by MetricsSniffer)
    requires org.glassfish.hk2.classmodel;

    // ── JDK management modules ────────────────────────────────────────────────
    // java.management (JMX) — used by MBeanExpression, Clock, MetricsMetadataHelper
    requires java.management;

    // ── OpenTelemetry (automatic modules) ────────────────────────────────────
    requires io.opentelemetry.api;

    // ── HK2 (automatic modules) ───────────────────────────────────────────────
    requires org.glassfish.hk2.api;
    requires org.glassfish.hk2.runlevel;
    requires hk2.config;

    // ── GlassFish deployment / admin APIs (automatic) ────────────────────────
    requires glassfish.api;
    requires config.api;
    requires common.util;

    // ── JDK modules ───────────────────────────────────────────────────────────
    requires java.logging;
    requires java.desktop;

    // ── Exported packages ─────────────────────────────────────────────────────
    exports fish.payara.microprofile.metrics;
    exports fish.payara.microprofile.metrics.activation;
    exports fish.payara.microprofile.metrics.admin;
    exports fish.payara.microprofile.metrics.cdi;
    exports fish.payara.microprofile.metrics.cdi.extension;
    exports fish.payara.microprofile.metrics.cdi.interceptor;
    exports fish.payara.microprofile.metrics.cdi.producer;
    exports fish.payara.microprofile.metrics.exception;
    exports fish.payara.microprofile.metrics.healthcheck;
    exports fish.payara.microprofile.metrics.impl;
    exports fish.payara.microprofile.metrics.jmx;
    exports fish.payara.microprofile.metrics.rest;
    exports fish.payara.microprofile.metrics.writer;

    // ── Deep opens for HK2 inhabitant scanning and CDI proxy generation ───────
    opens fish.payara.microprofile.metrics;
    opens fish.payara.microprofile.metrics.activation;
    opens fish.payara.microprofile.metrics.admin;
    opens fish.payara.microprofile.metrics.cdi;
    opens fish.payara.microprofile.metrics.cdi.extension;
    opens fish.payara.microprofile.metrics.cdi.interceptor;
    opens fish.payara.microprofile.metrics.cdi.producer;
    opens fish.payara.microprofile.metrics.exception;
    opens fish.payara.microprofile.metrics.healthcheck;
    opens fish.payara.microprofile.metrics.impl;
    opens fish.payara.microprofile.metrics.jmx;
    opens fish.payara.microprofile.metrics.rest;
    opens fish.payara.microprofile.metrics.writer;

    // ── SPI ───────────────────────────────────────────────────────────────────
    // Provider lives in this module — 'provides' is legal; META-INF/services retained for OSGi.
    provides jakarta.servlet.ServletContainerInitializer
            with fish.payara.microprofile.metrics.rest.MetricsServletContainerInitializer;
}