/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright (c) 2026 Payara Foundation and/or its affiliates. All rights reserved.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common Development
 * and Distribution License("CDDL") (collectively, the "License").  You
 * may not use this file except in compliance with the License.  You can
 * obtain a copy of the License at
 * https://github.com/payara/Payara/blob/main/LICENSE.txt
 * See the License for the specific
 * language governing permissions and limitations under the License.
 *
 * When distributing the software, include this License Header Notice in each
 * file and include the License file at legal/OPEN-SOURCE-LICENSE.txt.
 *
 * GPL Classpath Exception:
 * The Payara Foundation designates this particular file as subject to the "Classpath"
 * exception as provided by the Payara Foundation in the GPL Version 2 section of the License
 * file that accompanied this code.
 *
 * Modifications:
 * If applicable, add the following below the License Header, with the fields
 * enclosed by brackets [] replaced by your own identifying information:
 * "Portions Copyright [year] [name of copyright owner]"
 *
 * Contributor(s):
 * If you wish your version of this file to be governed by only the CDDL or
 * only the GPL Version 2, indicate your decision by adding "[Contributor]
 * elects to include this software in this distribution under the [CDDL or GPL
 * Version 2] license."  If you don't indicate a single choice of license, a
 * recipient has the option to distribute your version of this file under
 * either the CDDL, the GPL Version 2 or to extend the choice of license to
 * its licensees as provided above.  However, if you add GPL Version 2 code
 * and therefore, elected the GPL Version 2 license, then the option applies
 * only if the new code is made subject to such option by the copyright
 * holder.
 */

/**
 * JPMS module descriptor for the Payara MicroProfile Telemetry appserver integration module.
 *
 * OSGi metadata continues to be generated by Bnd (maven-bundle-plugin) — the dual-presence strategy.
 *
 * OpenTelemetry note: all OTel artifacts (opentelemetry-api, opentelemetry-context,
 * opentelemetry-instrumentation-annotations, opentelemetry-instrumentation-annotations-support,
 * opentelemetry-semconv) remain automatic modules. No OTel artifact ships module-info.java yet.
 * The Payara-internal opentelemetry-tracing-starter and telemetry-bootstrap are also automatic.
 *
 * SPI note: this module provides three service implementations:
 *   - TelemetryCdiExtension → jakarta.enterprise.inject.spi.Extension (CDI portable extension)
 *   - RestClientTelemetryListener → org.eclipse.microprofile.rest.client.spi.RestClientListener
 *   - Jersey ForcedAutoDiscoverable impls: kept in META-INF/services only, as jersey-common
 *     does not export org.glassfish.jersey.internal.spi for named-module 'provides' declarations.
 */
module fish.payara.microprofile.telemetry {

    // ── Spec and standard Jakarta APIs ───────────────────────────────────────
    // automatic module: microprofile-rest-client-api → microprofile.rest.client.api
    requires microprofile.rest.client.api;
    // named modules
    requires jakarta.annotation;
    requires jakarta.cdi;
    requires jakarta.inject;
    requires jakarta.ws.rs;

    // ── Payara internal modules (automatic) ───────────────────────────────────
    // internal-api-*.jar → internal.api  (org.glassfish.internal.api.*, org.glassfish.internal.deployment.*)
    requires internal.api;
    // opentelemetry-tracing-starter-*.jar → opentelemetry.tracing.starter  (fish.payara.opentracing.*)
    requires opentelemetry.tracing.starter;
    // telemetry-bootstrap-*.jar → telemetry.bootstrap  (fish.payara.telemetry.service.*)
    requires telemetry.bootstrap;
    // jaxrs-client-tracing-*.jar → jaxrs.client.tracing  (fish.payara.requesttracing.jaxrs.client.*)
    requires jaxrs.client.tracing;
    // requesttracing-core-*.jar → requesttracing.core  (fish.payara.nucleus.requesttracing.*)
    requires requesttracing.core;
    // payara-api-*.jar → payara.api  (fish.payara.notification.requesttracing.*)
    requires payara.api;
    // orb-connector-*.jar → orb.connector  (IIOP/EJB tracing)
    requires orb.connector;
    // jsr109-impl-*.jar → jsr109.impl  (JAX-WS tracing)
    requires jsr109.impl;

    // ── OpenTelemetry (automatic modules) ────────────────────────────────────
    // opentelemetry-api → io.opentelemetry.api
    requires io.opentelemetry.api;
    // opentelemetry-context → io.opentelemetry.context  (separate artifact from api)
    requires io.opentelemetry.context;
    // opentelemetry-instrumentation-annotations → io.opentelemetry.instrumentation_annotations
    requires io.opentelemetry.instrumentation_annotations;
    // opentelemetry-instrumentation-annotations-support → io.opentelemetry.instrumentation_annotations_support
    requires io.opentelemetry.instrumentation_annotations_support;
    // opentelemetry-semconv → io.opentelemetry.semconv
    requires io.opentelemetry.semconv;

    // ── MP Config (automatic) ────────────────────────────────────────────────
    // microprofile-config-api → org.eclipse.microprofile.config  (used by PayaraTracingServices, etc.)
    requires org.eclipse.microprofile.config;

    // ── GlassFish deployment / admin APIs (automatic) ────────────────────────
    // glassfish-api-*.jar → glassfish.api  (org.glassfish.api.invocation.*)
    requires glassfish.api;

    // ── Third-party named modules ─────────────────────────────────────────────
    // jersey-server (named) → org.glassfish.jersey.core.server
    requires org.glassfish.jersey.core.server;
    // jersey-common (named) → org.glassfish.jersey.core.common  (jersey.internal.spi, jersey.uri)
    requires org.glassfish.jersey.core.common;
    // jersey-client (named) → org.glassfish.jersey.core.client  (jersey.client.spi)
    requires org.glassfish.jersey.core.client;
    // weld-api (automatic) → weld.api
    requires weld.api;

    // ── CORBA / IIOP / JAX-WS (classpath — read via --add-reads) ───────────────
    // org.omg.CORBA/IOP/PortableInterceptor (ORB), jakarta.xml.soap.*, and
    // com.sun.xml.ws.api.message.* (JAX-WS Metro) are in jars that land on
    // the classpath (unnamed module) during Payara's module-aware compilation.
    // They cannot be acquired via 'requires'. The pom adds:
    //   --add-reads fish.payara.microprofile.telemetry=ALL-UNNAMED
    // so the compiler accepts references to those packages.

    // ── HK2 (automatic modules) ───────────────────────────────────────────────
    requires org.glassfish.hk2.api;

    // ── JDK modules ───────────────────────────────────────────────────────────
    requires java.logging;

    // ── Exported packages ─────────────────────────────────────────────────────
    exports fish.payara.microprofile.telemetry.tracing;
    exports fish.payara.microprofile.telemetry.tracing.ejb.iiop;
    exports fish.payara.microprofile.telemetry.tracing.jaxrs;
    exports fish.payara.microprofile.telemetry.tracing.jaxrs.client;
    exports fish.payara.microprofile.telemetry.tracing.jaxws;

    // ── Deep opens for HK2 and CDI proxy generation ───────────────────────────
    opens fish.payara.microprofile.telemetry.tracing;
    opens fish.payara.microprofile.telemetry.tracing.ejb.iiop;
    opens fish.payara.microprofile.telemetry.tracing.jaxrs;
    opens fish.payara.microprofile.telemetry.tracing.jaxrs.client;
    opens fish.payara.microprofile.telemetry.tracing.jaxws;

    // ── SPI ───────────────────────────────────────────────────────────────────
    provides jakarta.enterprise.inject.spi.Extension
            with fish.payara.microprofile.telemetry.tracing.TelemetryCdiExtension;
    provides org.eclipse.microprofile.rest.client.spi.RestClientListener
            with fish.payara.microprofile.telemetry.tracing.jaxrs.client.RestClientTelemetryListener;
}