#!/bin/bash
set -e;
DIRECTORY=$1;
NAMEADDON=$2
if [ -z "${DIRECTORY}" ]; then
  echo "First argument must be a directory!";
  exit 1;
fi
if [ -z "${NAMEADDON}" ]; then
  NAMEADDON="";
fi
if [ -f ${DIRECTORY}/*-[0-9][0-9][0-9][0-9][0-9][0-9]*.jar ]; then
  echo "JAR files generated by Eclipse detected, they need to be repacked (Eclipse corrupts indexes and classloader.getResources fails).";
else
  echo "No JAR files generated by Eclipse detected.";
  exit 0;
fi

function repack () {
  srcFile=$1
  echo "Repacking ${srcFile}";
  filename=$(basename -- "${srcFile}");
  baseFilename="${filename%.*}";
  tmpDir="/tmp/${baseFilename}";
  unzip "${srcFile}" -d "${tmpDir}" > /dev/null ;
  rm "${srcFile}";
  cd "${tmpDir}";
  zip -dg -q -r "${DIRECTORY}/${baseFilename}${NAMEADDON}.jar" . > /dev/null;
  rm -rf "${tmpDir}";
}

for srcFile in ${DIRECTORY}/*.jar; do
  repack $srcFile;
done
