/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright (c) 2026 Payara Foundation and/or its affiliates. All rights reserved.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common Development
 * and Distribution License("CDDL") (collectively, the "License").  You
 * may not use this file except in compliance with the License.  You can
 * obtain a copy of the License at
 * https://github.com/payara/Payara/blob/main/LICENSE.txt
 * See the License for the specific
 * language governing permissions and limitations under the License.
 *
 * When distributing the software, include this License Header Notice in each
 * file and include the License file at legal/OPEN-SOURCE-LICENSE.txt.
 *
 * GPL Classpath Exception:
 * The Payara Foundation designates this particular file as subject to the "Classpath"
 * exception as provided by the Payara Foundation in the GPL Version 2 section of the License
 * file that accompanied this code.
 *
 * Modifications:
 * If applicable, add the following below the License Header, with the fields
 * enclosed by brackets [] replaced by your own identifying information:
 * "Portions Copyright [year] [name of copyright owner]"
 *
 * Contributor(s):
 * If you wish your version of this file to be governed by only the CDDL or
 * only the GPL Version 2, indicate your decision by adding "[Contributor]
 * elects to include this software in this distribution under the [CDDL or GPL
 * Version 2] license."  If you don't indicate a single choice of license, a
 * recipient has the option to distribute your version of this file under
 * either the CDDL, the GPL Version 2 or to extend the choice of license to
 * its licensees as provided above.  However, if you add GPL Version 2 code
 * and therefore, elected the GPL Version 2 license, then the option applies
 * only if the new code is made font to such option by the copyright
 * holder.
 */

/**
 * JPMS module descriptor for the Payara MicroProfile Health appserver integration module.
 *
 * OSGi metadata continues to be generated by Bnd (maven-bundle-plugin) from the compiled
 * bytecode and pom.xml, so both MANIFEST.MF (OSGi) and module-info.class (JPMS) are
 * present in the produced JAR — the dual-presence strategy.
 *
 * Automatic-module note: hk2-api, hk2-config, web-glue, healthcheck-core, payara-api,
 * and Payara internal modules do not yet have their own module-info.java and appear on
 * the module path as automatic modules with the derived names used here.
 * microprofile-health-api ships an explicit module-info.class since 4.0.2.
 *
 * SPI note: this module is the provider of HealthCheckResponseProvider and
 * ServletContainerInitializer. Both implementation classes live in this module, so
 * cross-module 'provides' restrictions do not apply and explicit 'provides' declarations
 * are used here. The corresponding META-INF/services files are kept for OSGi runtime
 * compatibility (OSGi reads META-INF/services independently of JPMS).
 */
module fish.payara.microprofile.healthcheck {

    // ── Spec and standard Jakarta APIs ───────────────────────────────────────
    // named module since 4.0.2: microprofile-health-api-*.jar ships module-info.class
    requires org.eclipse.microprofile.health;
    // named modules
    requires jakarta.annotation;
    requires jakarta.cdi;
    requires jakarta.inject;
    requires jakarta.json;
    requires jakarta.servlet;
    requires jakarta.ws.rs;

    // ── Payara internal modules (all automatic: no module-info.java yet) ─────
    // microprofile-connector-*.jar → microprofile.connector
    requires microprofile.connector;
    // microprofile-common-*.jar → microprofile.common  (SetSecureMicroprofileConfigurationCommand, Constants)
    requires microprofile.common;
    // internal-api-*.jar → internal.api
    requires internal.api;
    // weld-integration-*.jar → weld.integration  (WeldDeployer)
    requires weld.integration;
    // payara-api-*.jar → payara.api  (fish.payara.notification.healthcheck.*)
    requires payara.api;
    // healthcheck-core-*.jar → healthcheck.core  (fish.payara.nucleus.healthcheck.*)
    requires healthcheck.core;

    // ── HK2 (automatic modules) ───────────────────────────────────────────────
    // hk2-api-*.jar → org.glassfish.hk2.api  (includes org.jvnet.hk2.annotations)
    requires org.glassfish.hk2.api;
    // hk2-runlevel-*.jar → org.glassfish.hk2.runlevel  (@RunLevel, @StartupRunLevel)
    requires org.glassfish.hk2.runlevel;
    // hk2-config-*.jar → hk2.config  (org.jvnet.hk2.config.*)
    requires hk2.config;

    // ── GlassFish deployment / admin APIs (automatic) ────────────────────────
    // glassfish-api-*.jar → glassfish.api  (org.glassfish.api.*)
    requires glassfish.api;
    // config-api-*.jar → config.api  (com.sun.enterprise.config.serverbeans.*, org.glassfish.config.support.*)
    requires config.api;
    // common-util-*.jar → common.util  (com.sun.enterprise.util.*, org.glassfish.common.util.*)
    requires common.util;
    // web-glue-*.jar → web.glue  (com.sun.enterprise.web.WebApplication/WebContainer/WebComponentInvocation)
    requires web.glue;

    // ── JDK modules not included in java.base ────────────────────────────────
    // java.util.logging (Logger, Level) — used across all health classes
    requires java.logging;
    // java.beans (PropertyChangeEvent, PropertyVetoException) — used in config listener
    requires java.desktop;

    // ── Exported packages ─────────────────────────────────────────────────────
    exports fish.payara.microprofile.healthcheck;
    exports fish.payara.microprofile.healthcheck.activation;
    exports fish.payara.microprofile.healthcheck.admin;
    exports fish.payara.microprofile.healthcheck.cdi.extension;
    exports fish.payara.microprofile.healthcheck.checks;
    exports fish.payara.microprofile.healthcheck.config;
    exports fish.payara.microprofile.healthcheck.response;
    exports fish.payara.microprofile.healthcheck.servlet;

    // ── Deep opens for runtime framework access ───────────────────────────────
    // HK2 inhabitant generator scans annotations in activation and admin classes at startup.
    // CDI container (Weld) creates proxies for CDI beans and the portable extension.
    // Unqualified opens also allow Mockito / JUnit reflection from the unnamed module
    // when running tests on the module path.
    opens fish.payara.microprofile.healthcheck;
    opens fish.payara.microprofile.healthcheck.activation;
    opens fish.payara.microprofile.healthcheck.admin;
    opens fish.payara.microprofile.healthcheck.cdi.extension;
    opens fish.payara.microprofile.healthcheck.checks;
    opens fish.payara.microprofile.healthcheck.config;
    opens fish.payara.microprofile.healthcheck.response;
    opens fish.payara.microprofile.healthcheck.servlet;

    // ── SPI ───────────────────────────────────────────────────────────────────
    // Both providers live in this module, so 'provides' is legal (no cross-module restriction).
    // META-INF/services files are retained for OSGi compatibility.
    provides org.eclipse.microprofile.health.spi.HealthCheckResponseProvider
            with fish.payara.microprofile.healthcheck.response.HealthCheckResponseProviderImpl;
    provides jakarta.servlet.ServletContainerInitializer
            with fish.payara.microprofile.healthcheck.servlet.HealthCheckServletContainerInitializer;
}