/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright (c) 2026 Payara Foundation and/or its affiliates. All rights reserved.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common Development
 * and Distribution License("CDDL") (collectively, the "License").  You
 * may not use this file except in compliance with the License.  You can
 * obtain a copy of the License at
 * https://github.com/payara/Payara/blob/main/LICENSE.txt
 * See the License for the specific
 * language governing permissions and limitations under the License.
 *
 * When distributing the software, include this License Header Notice in each
 * file and include the License file at legal/OPEN-SOURCE-LICENSE.txt.
 *
 * GPL Classpath Exception:
 * The Payara Foundation designates this particular file as subject to the "Classpath"
 * exception as provided by the Payara Foundation in the GPL Version 2 section of the License
 * file that accompanied this code.
 *
 * Modifications:
 * If applicable, add the following below the License Header, with the fields
 * enclosed by brackets [] replaced by your own identifying information:
 * "Portions Copyright [year] [name of copyright owner]"
 *
 * Contributor(s):
 * If you wish your version of this file to be governed by only the CDDL or
 * only the GPL Version 2, indicate your decision by adding "[Contributor]
 * elects to include this software in this distribution under the [CDDL or GPL
 * Version 2] license."  If you don't indicate a single choice of license, a
 * recipient has the option to distribute your version of this file under
 * either the CDDL, the GPL Version 2 or to extend the choice of license to
 * its licensees as provided above.  However, if you add GPL Version 2 code
 * and therefore, elected the GPL Version 2 license, then the option applies
 * only if the new code is made subject to such option by the copyright
 * holder.
 */

/**
 * JPMS module descriptor for the Payara MicroProfile JWT Authentication appserver integration module.
 *
 * OSGi metadata continues to be generated by Bnd (maven-bundle-plugin) — the dual-presence strategy.
 *
 * Automatic-module note: microprofile-jwt-auth-api, hk2-api, hk2-runlevel, hk2-config,
 * dol, web-glue, weld-integration, and other Payara internal modules appear as automatic
 * modules on the module path.
 *
 * SPI note: this module registers org.glassfish.jersey.internal.spi.ForcedAutoDiscoverable
 * via META-INF/services. Jersey's ForcedAutoDiscoverable SPI uses its own discovery mechanism
 * (not standard ServiceLoader in all paths), so the META-INF/services file is retained for
 * OSGi/classloader-based runtime discovery. A 'provides' declaration is not added here because
 * jersey-common does not export org.glassfish.jersey.internal.spi as a public named-module package.
 */
module fish.payara.microprofile.jwtauth {

    // ── Spec and standard Jakarta APIs ───────────────────────────────────────
    // automatic module: microprofile-jwt-auth-api → microprofile.jwt.auth.api
    requires microprofile.jwt.auth.api;
    // automatic module: microprofile-config-api → org.eclipse.microprofile.config
    requires org.eclipse.microprofile.config;
    // named modules
    requires jakarta.annotation;
    requires jakarta.cdi;
    requires jakarta.inject;
    requires jakarta.security;
    requires jakarta.ws.rs;
    requires jakarta.servlet;
    requires jakarta.json;

    // ── Payara internal modules (automatic) ───────────────────────────────────
    // microprofile-connector-*.jar → microprofile.connector
    requires microprofile.connector;
    // dol-*.jar → dol  (com.sun.enterprise.deployment.*)
    requires dol;
    // web-glue-*.jar → web.glue  (com.sun.enterprise.web.*)
    requires web.glue;
    // weld-integration-*.jar → weld.integration
    requires weld.integration;
    // internal-api-*.jar → internal.api
    requires internal.api;

    // ── Third-party named modules ─────────────────────────────────────────────
    // nimbus-jose-jwt (named MR) → com.nimbusds.jose.jwt
    requires com.nimbusds.jose.jwt;
    // jersey-common (named) → org.glassfish.jersey.core.common
    requires org.glassfish.jersey.core.common;

    // ── HK2 (automatic modules) ───────────────────────────────────────────────
    requires org.glassfish.hk2.api;
    requires org.glassfish.hk2.runlevel;
    requires hk2.config;

    // ── GlassFish deployment / admin APIs (automatic) ────────────────────────
    requires glassfish.api;
    requires config.api;
    // common-util-*.jar → common.util  (org.glassfish.common.util.*)
    requires common.util;
    // grizzly-http (named) → org.glassfish.grizzly.http  (org.glassfish.grizzly.http.util.*)
    requires org.glassfish.grizzly.http;
    // soteria (named) → org.glassfish.soteria  (org.glassfish.soteria.cdi.*)
    requires org.glassfish.soteria;

    // ── JDK modules ───────────────────────────────────────────────────────────
    requires java.logging;
    requires java.desktop;

    // ── Exported packages ─────────────────────────────────────────────────────
    exports fish.payara.microprofile.jwtauth;
    exports fish.payara.microprofile.jwtauth.activation;
    exports fish.payara.microprofile.jwtauth.cdi;
    exports fish.payara.microprofile.jwtauth.eesecurity;
    exports fish.payara.microprofile.jwtauth.jaxrs;
    exports fish.payara.microprofile.jwtauth.jwt;

    // ── Deep opens for HK2 inhabitant scanning and CDI proxy generation ───────
    opens fish.payara.microprofile.jwtauth;
    opens fish.payara.microprofile.jwtauth.activation;
    opens fish.payara.microprofile.jwtauth.cdi;
    opens fish.payara.microprofile.jwtauth.eesecurity;
    opens fish.payara.microprofile.jwtauth.jaxrs;
    opens fish.payara.microprofile.jwtauth.jwt;
}