CREATE TABLE EJB__TIMER__TBL (
CREATIONTIMERAW      DECIMAL(18,0) NOT NULL, 
"BLOB"               BLOB(1024K), 
TIMERID              VARCHAR(255)  NOT NULL, 
CONTAINERID          DECIMAL(18,0) NOT NULL, 
OWNERID              VARCHAR(255), 
STATE                INTEGER       NOT NULL, 
PKHASHCODE           INTEGER       NOT NULL, 
INTERVALDURATION     DECIMAL(18,0) NOT NULL, 
INITIALEXPIRATIONRAW DECIMAL(18,0) NOT NULL, 
LASTEXPIRATIONRAW    DECIMAL(18,0) NOT NULL,
SCHEDULE             VARCHAR(255),
APPLICATIONID        DECIMAL(18,0) NOT NULL,
PRIMARY KEY (TIMERID)
);
CREATE INDEX EJB__TIMER__TBL.IDX1 KEY(TIMERID)
;
