CREATE TABLE EJB__TIMER__TBL (
CREATIONTIMERAW      NUMERIC(20,0)  NOT NULL,
BLOB                 IMAGE          NULL,
TIMERID              VARCHAR(255)   NOT NULL,
CONTAINERID          NUMERIC(20,0)  NOT NULL,
OWNERID              VARCHAR(255)   NULL,
STATE                INTEGER        NOT NULL,
PKHASHCODE           INTEGER        NOT NULL,
INTERVALDURATION     NUMERIC(20,0)  NOT NULL,
INITIALEXPIRATIONRAW NUMERIC(20,0)  NOT NULL,
LASTEXPIRATIONRAW    NUMERIC(20,0)  NOT NULL,
SCHEDULE             VARCHAR(255)   NULL,
APPLICATIONID        NUMERIC(20,0)  NOT NULL,
CONSTRAINT PK_EJB__TIMER__TBL PRIMARY KEY (TIMERID) 
) 
