#!/bin/sh
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2011 Oracle and/or its affiliates. All rights reserved.
#
# The contents of this file are subject to the terms of either the GNU
# General Public License Version 2 only ("GPL") or the Common Development
# and Distribution License("CDDL") (collectively, the "License").  You
# may not use this file except in compliance with the License.  You can
# obtain a copy of the License at
# https://glassfish.dev.java.net/public/CDDL+GPL_1_1.html
# or packager/legal/LICENSE.txt.  See the License for the specific
# language governing permissions and limitations under the License.
#
# When distributing the software, include this License Header Notice in each
# file and include the License file at packager/legal/LICENSE.txt.
#
# GPL Classpath Exception:
# Oracle designates this particular file as subject to the "Classpath"
# exception as provided by Oracle in the GPL Version 2 section of the License
# file that accompanied this code.
#
# Modifications:
# If applicable, add the following below the License Header, with the fields
# enclosed by brackets [] replaced by your own identifying information:
# "Portions Copyright [year] [name of copyright owner]"
#
# Contributor(s):
# If you wish your version of this file to be governed by only the CDDL or
# only the GPL Version 2, indicate your decision by adding "[Contributor]
# elects to include this software in this distribution under the [CDDL or GPL
# Version 2] license."  If you don't indicate a single choice of license, a
# recipient has the option to distribute your version of this file under
# either the CDDL, the GPL Version 2 or to extend the choice of license to
# its licensees as provided above.  However, if you add GPL Version 2 code
# and therefore, elected the GPL Version 2 license, then the option applies
# only if the new code is made subject to such option by the copyright
# holder.


GLASSFISH_HOME=${GLASSFISH_HOME:-"/opt/glassfishvm/glassfish3"}

case "$1" in
start)
    if [ ! -e /etc/opt/glassfishvm/image_name ]; then
        echo "Image not configured, glassfish startup exiting"
        return
    fi
    image_name=`cat /etc/opt/glassfishvm/image_name`
    node_name=`echo $image_name\_node`
    das_ip=`cat /etc/opt/glassfishvm/das_info`
	das_port=`cat /etc/opt/glassfishvm/das_port`
# reset networking interfaces on first boot. 
	if [ ! -e /etc/opt/glassfishvm/initial_config_done ]; then
  		/opt/glassfishvm/bin/initial-setup.sh
    fi
# get the IP address of this instance
    intf=`awk < /proc/net/dev '
    {   if ($1 ~ /^eth/) {
            split($1,field, ":")

            print(field[1])
        }
    }'`
    ip_address=`/sbin/ifconfig $intf  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}'`

	if [ ! -e /etc/opt/glassfishvm/initial_config_done ]; then
# first time boot, we declare ourselves to the DAS as a new node and a new instance
		cluster_name=`cat /etc/opt/glassfishvm/cluster_info`
		ip_address=`/sbin/ifconfig $intf  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}'`
		echo $ip_address >/etc/opt/glassfishvm/configured_ip
#		$GLASSFISH_HOME/glassfish//bin/asadmin -H $das_ip -p $das_port create-local-instance --node $ip_address --cluster $cluster_name --nodedir $GLASSFISH_HOME $image_name
		$GLASSFISH_HOME/glassfish/bin/asadmin -H $das_ip -p $das_port create-node-ssh --nodehost $ip_address --installdir $GLASSFISH_HOME $node_name
		$GLASSFISH_HOME/glassfish/bin/asadmin -H $das_ip -p $das_port create-instance --node $node_name --cluster $cluster_name $image_name
  		touch /etc/opt/glassfishvm/initial_config_done
		return
    else
# we must check that our IP address has not changed since the last time we booted.
        configured_ip_address=`cat /etc/opt/glassfishvm/configured_ip`
        if [ $ip_address != $configured_ip_address ]; then
            echo "IP address changed from $configured_ip_address to $ip_address"
		    $GLASSFISH_HOME/glassfish/bin/asadmin -H $das_ip -p $das_port update-node-ssh --nodehost $ip_address $node_name
    		echo $ip_address >/etc/opt/glassfishvm/configured_ip
        else
            echo "Unchanged IP address at $ip_address"
        fi
	fi
#    we don't startup glassfish automatically as we rely on the DAS.
    $GLASSFISH_HOME/glassfish/bin/asadmin start-domain >/dev/null
    ;;
stop)
    $GLASSFISH_HOME/glassfish/bin/asadmin stop-domain >/dev/null
    ;;
restart)
    $GLASSFISH_HOME/glassfish/bin/asadmin restart-domain >/dev/null
    ;;
*)
    echo "usage: $0 (start|stop|restart|help)"
esac


