package org.glassfish.elasticity.expression;

public enum TokenType {
	MULT, DIV, PLUS, MINUS, OPAR, CPAR, OBRACE, CBRACE, 
	LOGICAL_AND, LOGICAL_OR, LOGICAL_NOT, BIT_AND, BIT_OR,
	DOUBLE, INTEGER, TRUE, FALSE, STRING, IDENTIFIER, 
	AT, HASH, PERCENT, CARET, DOT,
	LT, GT, LTE, GTE, EQ, EQEQ,
	WHITESPACE,
	UNKNOWN, EOSTREAM
}
